Copy over travis configurations from theochem/iodata
These files are needed for TravisCI and are the standards used in
QuantumElephant and Ayers group for managing github repo's.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,11 +1,225 @@
+# TEMPLATED FROM https://raw.githubusercontent.com/theochem/python-cython-ci-example/master/.travis.yml
+
+env:
+  matrix:
+  # - MYCONDAPY=3.5
+  - MYCONDAPY=3.6
+  global:
+    # Anaconda
+    # - secure:
+    # Github
+    - secure: nEtQVqrlM+IuI7Z89+ZDs+F+VFX8fOWd1TCFLVnAORhQdnX8aCE7lNBDTsNGWVfBX2/Rc3+j0P7nKcl/5FkVTFrpVSXFpuUwrjuPP8ZRdkxiWvYDK3S15e8U8FCs6S7PQBCLj8prpBFaH2hXTNfeVJ2kLYHze0XR4iTc/4hY+Hai5nd0FFzwGZH5t2xBJpFq8b71bEfXV99qIZFqeUd0AKIegktvTfoQsC/9EdbsviOaNcoipQAGpkrOg7kVgtBg7C2X8Y4qpyNlV/Ltz7n9AB2D3bPqZ3+scBzsez4C3HByRDni6nKAN5JXnhJ4TotGVAZEvHyWi62eSvwXG5OV4+aORfVcTbI4evLPA0DdrFHkK5Z1jWRqpiUftdKZ0yq0igc0Z+L9N2Vexplhrb8JHKiCjwKE/ZvlOuIMh5J3XpAmWTR5uU7Z2OqHZTbWdYSwTlCrrEtbUNE1AdYdaS8As/CMxwS+a8cgMi4mLzURTA7QhYb8g0qT74kyPjhkq4UXH4k0ZKNPuAFu0xLK/GWeEQ6dTXNMsOrNv5o/NOqEwKUdf6IbFZ4N0bt+WUPscNtZqag+yQ2q+oAVm6qMx2bddJW79Gn2HbTr1bydeUd/8Th0Wus71MlMtB+PTF00uQ2Pa2vNrzem2Rc49qfLW0bsFEZ4fzy3mn8VgFqvh4Pxe6U=
+    # PyPi
+    # - secure:
+    - PROJECT_NAME=wfns
+    - GITHUB_REPO_NAME=quantumelephant/olsens
+    - CONDA_PKG_NAME_PY=wfns
+
+####
+# EVERYTHING BELOW THIS LINE WILL BE COPIED INTO OTHER YMLs
+####
+
+# Do not use Travis Python to save some time.
+language: generic
+os:
+  - linux
+  - osx
+osx_image: xcode8.3
+dist: trusty
+sudo: false
+
+matrix:
+  # We only test on Linux with one specific Python version, unless we make a release. All
+  # other cases are allowed to fail and will exit early. With the fast_finish option,
+  # travis will send a status update to github as soon as the non-allowed-to-fail has
+  # finished. This speeds up testing in PRs.
+  #
+  # This is not ideal. It would be better to run just one item from the build matrix when
+  # not preparing a release. This is not possible on Travis. There are several tickets on
+  # travis-ci related to this limitation.
+  #
+  #    https://github.com/travis-ci/travis-ci/issues/7451
+  #    https://github.com/travis-ci/travis-ci/issues/7149
+  #    https://github.com/travis-ci/travis-ci/issues/2778
+  #    ...
+  fast_finish: true
+  allow_failures:
+  - os: osx
+
+
+cache:
+  directories:
+    - $HOME/download # Sufficient to add miniconda.sh to TRAVIS cache.
+    - $HOME/miniconda # Add the installation to TRAVIS cache.
+
+before_cache:
+- if ! [[ $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
+- rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
+- pip uninstall -y cardboardlint # Cardboardlint always installs even if no changes are made.
+
+branches:
+  only:
+    - master
+    - /^[0-9]+\.[0-9]+(\.[0-9]+)?([ab][0-9]+)?$/
+
+before_install:
+# Get miniconda. Take the right version, so re-installing python is hopefully not needed.
+- if test -e $HOME/miniconda/bin; then
+    echo "miniconda already installed.";
+  else
+    echo "Installing miniconda.";
+    rm -rf $HOME/miniconda;
+    mkdir -p $HOME/download;
+    if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi;
+    if [ "${MYCONDAPY}" = "2.7" ]; then
+      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
+        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
+      else
+        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
+      fi;
+    else
+      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
+        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
+      else
+        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
+      fi;
+    fi;
+    bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
+  fi
+
+
 install:
+- source $HOME/miniconda/bin/activate
+- hash -r
+# Configure conda and get a few essentials
+- conda config --set always_yes yes
+- conda config --add channels theochem
+- conda install -q conda conda-build
+
+# Set the version info from the git tag
+- git fetch origin --tags &&
+  export PROJECT_VERSION=$(python tools/gitversion.py) &&
+  python tools/gitversion.py python > ${PROJECT_NAME}/version.py;
+
+# Get a list of all build and runtime dependencies.
+# This should become easier, without the copy to conda.recipe.ugly.
+- conda render tools/conda.recipe > tools/conda.recipe/rendered.yaml
+- CONDA_DEPENDENCIES=$(python -c "from yaml import load;
+    req1 = load(open('tools/conda.recipe/rendered.yaml'))['requirements'];
+    deps = req1['build'] + req1['run'];
+    print(' '.join(set(dep.split()[0] for dep in deps)))")
+
+# Get the right python version for building. This only does something for 3.5.
+# Install extra package needed to make things work. Most things can be listed as
+# dependencies on metal.yaml and setup.py, unless setup.py already imports them.
+# Install conda tools for packaging and uploading
+- conda install -q python=${MYCONDAPY} anaconda-client ${CONDA_DEPENDENCIES}
+# Install more recent stuff with pip
+- pip install --upgrade pylint codecov coverage pycodestyle pydocstyle
+# Show conda info for debugging
+- conda info -a
+
 # Install the latest cardboardlinter
 - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
     pip install --upgrade git+https://github.com/theochem/cardboardlint.git@master#egg=cardboardlint;
   fi
 
 script:
-# Run the cardboardlinter, in case of pull requests
+# Static linting
+# --------------
 - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
-    cardboardlinter --refspec $TRAVIS_BRANCH;
+    cardboardlinter --refspec $TRAVIS_BRANCH -f static;
   fi
+
+# Unit tests and dynamic linting
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+- if [[ $TRAVIS_TAG ]]; then
+    conda build -q tools/conda.recipe &&
+    conda install --use-local ${CONDA_PKG_NAME_PY} &&
+    (cd; nosetests ${PROJECT_NAME} -v --detailed-errors) &&
+    conda uninstall ${CONDA_PKG_NAME_PY};
+  else
+    python setup.py build_ext -i --define CYTHON_TRACE_NOGIL &&
+    nosetests ${PROJECT_NAME}
+         -v --detailed-errors --with-coverage --cover-package=${PROJECT_NAME}
+         --cover-tests --cover-inclusive --cover-branches &&
+    coverage xml -i &&
+
+    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
+       cardboardlinter --refspec $TRAVIS_BRANCH -f 'dynamic';
+    fi
+  fi
+
+# Make CPP and PY source package for github deployment
+- if [[ $TRAVIS_TAG ]]; then
+    python setup.py sdist;
+  fi
+
+# Some other stuff
+# ----------------
+
+# Compile documentation
+- if [[ -e doc ]]; then
+    (cd doc; make html);
+  fi
+
+after_success:
+# Upload the coverage analysis
+- codecov -f coverage.xml
+
+before_deploy:
+# Try to set some env vars to configure deployment.
+# Please keep the following lines. They will be used again as soon as it is supported on
+# travis. See https://github.com/travis-ci/dpl/issues/613
+#- export IS_PRERELEASE=$(python -c 'import os; tt=os.environ["TRAVIS_TAG"]; print("true" if ("a" in tt or "b" in tt) else "false")')
+#- echo ${IS_PRERELEASE}
+- export ANACONDA_LABEL=$(python -c 'import os; tt=os.environ["TRAVIS_TAG"]; print("alpha" if ("a" in tt) else ("beta" if "b" in tt else "main"))')
+- echo ${ANACONDA_LABEL}
+
+# In deployment, the env var TRAVIS_TAG contains the name of the current version, if any.
+deploy:
+- provider: releases
+  skip_cleanup: true
+  api_key: ${GITHUB_TOKEN}
+  file: dist/${PROJECT_NAME}-${TRAVIS_TAG}.tar.gz
+  on:
+    repo: ${GITHUB_REPO_NAME}
+    tags: true
+    condition: "$MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux && $TRAVIS_TAG == *[ab]*"
+  prerelease: true
+
+- provider: releases
+  skip_cleanup: true
+  api_key: ${GITHUB_TOKEN}
+  file: dist/${PROJECT_NAME}-${TRAVIS_TAG}.tar.gz
+  on:
+    repo: ${GITHUB_REPO_NAME}
+    tags: true
+    condition: "$MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux && $TRAVIS_TAG != *[ab]*"
+  prerelease: false
+
+- provider: script
+  skip_cleanup: true
+  script: anaconda -t $ANACONDA_TOKEN upload --force -l ${ANACONDA_LABEL} ${HOME}/miniconda/conda-bld/*/${PROJECT_NAME}-*.tar.bz2
+  on:
+    repo: ${GITHUB_REPO_NAME}
+    tags: true
+
+- provider: pypi
+  skip_cleanup: true
+  user: theochem
+  password: ${PYPI_PASSWD}
+  on:
+    repo: ${GITHUB_REPO_NAME}
+    tags: true
+    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
+
+- provider: pages
+  skip_cleanup: true
+  github_token: ${GITHUB_TOKEN}
+  project_name: ${PROJECT_NAME}
+  local_dir: doc/_build/html
+  on:
+    repo: ${GITHUB_REPO_NAME}
+    condition: "-e doc && $TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
+    tags: true
